name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: builddir
      run: mkdir build; cd build
    - name: cmake
      run: cmake ..
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck
